### PR TITLE
fix - AssertionError: Path expected

### PR DESCRIPTION
**Pull request by kuznetsov-online**

### CODE REVIEW

**Comment by austinkelleher** [comment]
Hey @FiW. Thanks for the PR. I'm trying to understand why this would actually happen. I added several tests (merged into master). Can you possibly rebase with master and add a test case that causes this behavior? Thanks!

**Comment by austinkelleher** [comment]
For the record, I ran the tests using Lasso 1, Lasso 2, and Lasso 3. What version of Lasso are you using by the way?

**Comment by FiW** [comment]
Thank you.

PS: I using Lasso 3. I have received error 'AssertionError: Path expected', when I used this plugin in project. Like this https://github.com/lasso-js/lasso-imagemin/issues/2

**Comment by austinkelleher** [comment]
Never mind I was able to reproduce this by passing a dependency type that is not a support image format such as a `.js` file.

```js
require('lasso').lassoPage({
    dependencies: [
      "require-run: ./index.js",
      "./*.svg"
    ]
})
```

Thanks for the PR!

**Comment by austinkelleher** [comment]
I'm making a few more safety changes to ensure that we only ever optimize images that are in the plugin types then I will publish this module. Thanks again for your change.

**Comment by austinkelleher** [comment]
Published `lasso-imagemin@1.0.8`

**Pull request merged**
